name: dart_poeditor
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  http: ^0.13.4
  http_interceptor: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dotenv: ^4.0.1
