name: dart_poeditor
description: A dart library for poeditor
homepage: https://github.com/nombrekeff/flutter_poeditor
version: 0.0.1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  http: ^0.13.4
  http_interceptor: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dotenv: ^4.0.1
